version: '3.7'

networks:
  cloud-hole:
    name: cloud-hole-net
    ipam:
      config:
        - subnet: 172.16.241.0/24

services:
  traefik:
    container_name: traefik
    image: traefik
    logging:
      driver: $LOG_DRIVER
    restart: unless-stopped
    healthcheck:
      test: traefik healthcheck --ping
    ports:
      - "443:443"
      - "53:53"
      - "53:53/udp"
      - "853:853"
    networks:
      cloud-hole:
        ipv4_address: 172.16.241.10
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_tls-resolver_ACME_EMAIL=$ACME_EMAIL
    volumes:
      - ./secrets/acme.json:/etc/traefik/acme.json
      - ./secrets/htpasswd:/etc/traefik/htpasswd:ro
      - ./conf/traefik.yml:/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
  pi-hole:
    container_name: pi-hole
    image: pihole/pihole
    logging:
      driver: $LOG_DRIVER
    restart: unless-stopped
    depends_on:
      - coredns-outbound
    networks:
      cloud-hole:
        ipv4_address: 172.16.241.20
    environment:
      - TZ
      - DNS1=127.0.0.11
      - DNS2=no
      - VIRTUAL_HOST=pi-hole.cloud-hole-net
      - WEBPASSWORD=
    volumes:
      - ./etc/pi-hole:/etc/pihole
      - ./etc/dnsmasq:/etc/dnsmasq.d
      # workaround to make DNSMASQ compatible with Docker - https://github.com/pi-hole/docker-pi-hole/issues/410
      - ./conf/pi-hole.resolv.conf:/etc/resolv.conf:ro
    dns:
      - 172.16.241.30
    labels:
      - traefik.enable=true
      - traefik.http.services.pi-hole.loadbalancer.server.port=80
      - traefik.tcp.services.pi-hole.loadbalancer.server.port=53
      - traefik.udp.services.pi-hole.loadbalancer.server.port=53
      # admin reverse proxy
      - traefik.http.routers.pi-hole-dashboard.rule=Host(`$PI_HOLE_SUB_DOMAIN.$DOMAIN`)
      - traefik.http.routers.pi-hole-dashboard.entrypoints=websecure
      - traefik.http.routers.pi-hole-dashboard.tls.certresolver=tls-resolver
      - traefik.http.routers.pi-hole-dashboard.middlewares=pi-hole-dashboard-auth,pi-hole-dashboard-path
      - traefik.http.middlewares.pi-hole-dashboard-path.addprefix.prefix=/admin/
      - traefik.http.middlewares.pi-hole-dashboard-auth.basicauth.usersfile=/etc/traefik/htpasswd
      # dns over tcp reverse proxy
      - traefik.tcp.routers.pi-hole-dns-tcp.rule=HostSNI(`*`)
      - traefik.tcp.routers.pi-hole-dns-tcp.entrypoints=dns
      # dns over udp reverse proxy
      - traefik.udp.routers.pi-hole-dns-udp.entrypoints=dns-udp
      # dns over tls tcp reverse proxy
      - traefik.tcp.routers.pi-hole-dns-tls-tcp.rule=HostSNI(`$DNS_SUB_DOMAIN.$DOMAIN`)
      - traefik.tcp.routers.pi-hole-dns-tls-tcp.entrypoints=dnssecure
      - traefik.tcp.routers.pi-hole-dns-tls-tcp.tls.certresolver=tls-resolver
  coredns-outbound:
    container_name: coredns-outbound
    image: coredns/coredns
    logging:
      driver: $LOG_DRIVER
    restart: unless-stopped
    networks:
      cloud-hole:
        ipv4_address: 172.16.241.30
    environment:
      - UPSTREAM_DNS_1
      - UPSTREAM_DNS_2
      - UPSTREAM_DNS_HOSTNAME
    volumes:
      - ./conf/outbound.corefile.conf:/Corefile:ro
