log:
  level: INFO

ping: {}

entryPoints:
  websecure:
    address: ":443"
  dns:
    address: ":53"
  dns-udp:
    address: ":53/udp"
  dnssecure:
    address: ":853"

providers:
  docker:
    network: cloud-hole-net
    exposedByDefault: false

certificatesResolvers:
  tls-resolver:
    acme:
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
      preferredChain: 'ISRG Root X1'
      httpChallenge:
        entryPoint: websecure
